### ISSUE TITLE
./guess.sh does not output anything into the terminal

### ISSUE THREAD

**Issue by ProGamerGov** [llSourcell/tensorflow_image_classifier#1]
```
ubuntu@ubuntu-VirtualBox:~/tensorflow_image_classifier$ sudo ./guess.sh /home/ubuntu/tensorflow_image_classifier/my_own_classifier /home/ubuntu/tensorflow_image_classifier/prisma/prisma-stpauls.jpg
ubuntu@ubuntu-VirtualBox:~/tensorflow_image_classifier$ 
```

**Comment by rahuldeo2047** [comment]
try removing "2> /dev/null" from guess.sh to check.

**Comment by ProGamerGov** [comment]
I removed the "2> /dev/null" from guess.sh, and now receive a visible error message.

```
ubuntu@ubuntu-VirtualBox:~/tensorflow_image_classifier$ ./guess.sh /home/ubuntu/tensorflow_image_classifier/my_own_classifier /home/ubuntu/tensorflow_image_classifier/thumb_img86798_ac828794883f3bb9.jpg
./guess.sh: 2: cd: can't cd to /tf_files
Traceback (most recent call last):
  File "label_image.py", line 1, in <module>
    import tensorflow as tf
  File "/tensorflow/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/tensorflow/tensorflow/python/__init__.py", line 48, in <module>
    from tensorflow.python import pywrap_tensorflow
ImportError: cannot import name pywrap_tensorflow
ubuntu@ubuntu-VirtualBox:~/tensorflow_image_classifier$ 

```

**Comment by arthurgrevin** [comment]
I have the same error trace. Did you find a way to solve this ?

**Comment by AntonEryomin** [comment]
Hi!

I've deleted this: "2> /dev/null"
But I have a different error message:

➜  my_own_classifier ./guess.sh ~/Documents/CNN/5minutes/my_own_classifier/ ~/Documents/CNN/5minutes/my_own_classifier/testImage.jpg
: not foundess.sh

How can I analyse what does this script do?

**Comment by AntonEryomin** [comment]
I've found solution, just be careful about the path and don't forget that you use scripts through docker container, find out more information about how is it work.

**Comment by ProGamerGov** [comment]
To solve the issue, I made a new Ubuntu VM in Virutalbox where I installed tensorflow using pip. I then ran the script `label_image.py` directly.

**Comment by abramjs** [comment]
@OdinO4ka I've the same issue, 
: not foundess.sh
could you please better explain how you solved it?

**Comment by flappyshabeer** [comment]
Try to install tensorflow and change the directory from root to the folder where the program has place the classifier
Then open terminal and enter : sudo python label_image.py mydirectory/img.jpeg

**Comment by achirand** [comment]
Try  this way can solve this problem.
First, open **label_image.py**, change "/tf_files/retrained_labels.txt"  to "/home/liuliu/python/liuliu_classifier/retrained_labels.txt"
and   "/tf_files/retrained_graph.pb"  to "/home/liuliu/python/liuliu_classifier/retrained_graph.pb" 
then enter this command in terminal:  **sudo python ./src/label_image.py   /home/liuliu/python/test/test11.jpg**
