### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'keys'

### ISSUE THREAD

**Issue by iklobato** [llSourcell/tensorflow_image_classifier#13]
> SO: Ubuntu 16.04
> Docker: 2.5.0
> Python3: 3.5.2
> Python2 : 2.7.12
> Tensorflow: 1.3.0 (intalled at both Python)

Made commands as root
> ./build.sh
> ./train.sh /<images/path>/tensorflow_image_classifier-master/pictures/training

Folders structure:
- tensorflow_image_classifier-master
  - src
  - pictures
       - test
       - training
          - cats
          - dogs

I honestly dont know why im getting this error

```
root@mw:~<path>/tensorflow_image_classifier-master# ./train.sh /<path>/tensorflow_image_classifier-master/pictures/training
Image directory '/tf_files/data' not found.
Traceback (most recent call last):
  File "tensorflow/examples/image_retraining/retrain.py", line 824, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "tensorflow/examples/image_retraining/retrain.py", line 721, in main
    class_count = len(image_lists.keys())
AttributeError: 'NoneType' object has no attribute 'keys'
```

EDIT: It was without the `data` folder

**Comment by VirgilMa** [comment]
same here too

**Comment by klango** [comment]
Same here, were you guys able to fix this?

**Comment by MathiasHaudgaard** [comment]
Getting the same error. Has this been fixed yet?

**Comment by MathiasHaudgaard** [comment]
@llSourcell do you know what causes this problem?

**Comment by rubenCodeforges** [comment]
Same here but looks like the repo is dead

**Comment by gstok** [comment]
You can use the latest tensorflow under ubuntu and python27, In fact, this is an official example of tensorflow [https://github.com/tensorflow/hub/tree/master/examples/image_retraining](url), I have successfully built the official tutorial.

**Comment by asnair** [comment]
This happens because the folder hierarchy isn't correct. Instead of having your data in
`/some/path/to/tensorflow_image_classifier-master/data` then categories, you're missing the /data/ part. Your folder must be named 'data' and contain folder categories:
/some/path/to/classifier/**data**/class1
/some/path/to/classifier/**data**/class2

Once this is fixed you will get more errors, but not the same errors. Using the official tutorial is probably easier (EDIT: https://github.com/tensorflow/hub/tree/master/examples/image_retraining )

**Comment by csabag** [comment]
you have to give the full path of your classifier folder without the trailing /
E.g. /some/path/to/classifier

**Comment by fanyoujian** [comment]
hello how to deal this bug?

**Comment by klango** [comment]
> hello how to deal this bug?

This is not a Bug. Its related to the full path including the /data folder.

**Comment by knightowl2704** [comment]
Hey! Take care of the empty spaces between the directory names and it will work. Even the space between  --image_directory=/your/path/to/training/folder/here
If space is encountered in any folder name leading to the training images directory, write it as : 
for ex : folder name  =>  "training images"
cd training\ images
This will work.
